modLoader = "kotlinforforge"
loaderVersion = "[4.1,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "resource_nodes"
version = "${version}"
displayName = "Resource Nodes"
authors = "Ricky12Awesome"
description = '''
adds Resources nodes
'''
#logoFile = ""

[[dependencies.resource_nodes]]
modId = "forge"
mandatory = true
versionRange = "[45,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.resource_nodes]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.resource_nodes]]
modId = "architectury"
mandatory = true
versionRange = "[8.1.79,)"
ordering = "AFTER"
side = "BOTH"